# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Quantum Physics
author: Wolfgang Löffler
copyright: "2025, no license yet"
# logo: figures/qist-iqp-small.gif

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: iqp-book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - bibliography.bib

# can't use this, development.md
# only_build_toc_files: true

sphinx:
  config:
    html_favicon: favicon.ico
    # html_extra_path:
    #   - _assets
    # html_js_files:
    # - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_show_copyright: true
    html_theme_options: # ugly hack because show_navbar_depth doesn't work below, wipes other options below
      "show_navbar_depth": 2

  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    - sphinx.ext.imgconverter
    - sphinx.ext.mathjax
    - sphinx-mathjax-offline
    - sphinx_exercise
    - sphinx_togglebutton

parse:
  myst_enable_extensions:
    - amsmath
    # - attrs_block
    - colon_fence
    - dollarmath
    - linkify
    - substitution
  myst_dmath_double_inline: true
  myst_substitutions:
    slidetag: ''
    # slidetag: '`[slide]`' # use this to see the slide tags!


# Information about where the book exists on the web
repository:
  url: https://github.com/wolfgangasdf/iqp-book  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitLab buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  show_navbar_depth: 2 # doesn't work https://github.com/executablebooks/jupyter-book/issues/1134
  use_issues_button: false
  use_repository_button: true
  comments:
    hypothesis: true  # Hypothesis for comments
  extra_footer: |
    <p>
    All material Copyright © 2025 Wolfgang Löffler.<br>
    License: none yet.
    </p>
